spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        hikari:
            minimumIdle: 5
            maximumPoolSize: 20
            idleTimeout: 30000
            poolName: SpringBootJPAHikariCP
            maxLifetime: 2000000
            connectionTimeout: 30000

    jpa:
        hibernate:
            ddl-auto: create-drop
        generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    kafka:
        bootstrap-servers: localhost:9092

    mail:
        username: biuro@bike-rental.com

server:
    port: 8081

